
name: Reproduce url.parse() Deprecation Warning

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test-cache-warning:
    runs-on: ubuntu-latest
    # env:
    #   TARGET_DOMAIN: example.com
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js with caching
        uses: actions/setup-node@v5
        # uses: lmvysakh/setup-node@resolve_punycode
        with:
          node-version: 20
          cache: npm
          always-auth: false
          check-latest: false
          package-manager-cache: true
          # cache-dependency-path: package-lock.json   # <-- Explicitly point to lock file

      
      - name: Install dependencies
        run: npm ci
        
      # - run: npm install 
      
      - name: Run tests
        run: npm test